#!/bin/sh

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets
run_eww() {
	${EWW} --config "$CFG" open-many \
		background --arg background:screen=0 \
		profile --arg profile:screen=0 \
		system --arg system:screen=0 \
		clock --arg clock:screen=0 \
		uptime --arg uptime:screen=0 \
		music --arg music:screen=0 \
		github --arg github:screen=0 \
		reddit --arg reddit:screen=0 \
		twitter --arg twitter:screen=0 \
		youtube --arg youtube:screen=0 \
		weather --arg weather:screen=0 \
		apps --arg apps:screen=0 \
		mail --arg mail:screen=0 \
		logout --arg logout:screen=0 \
		sleep --arg sleep:screen=0 \
		reboot --arg reboot:screen=0 \
		poweroff --arg poweroff:screen=0 \
		folders --arg folders:screen=0
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
		background profile system clock uptime music github \
		reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm "$FILE"
fi
